//
// DebugAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class DebugAPI: APIBase {
    /**
     Check the API state
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func stats(completion: ((data: Stats?, error: ErrorType?) -> Void)) {
        statsWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Check the API state
     - GET /
     - Useful for debugging - pinging your servers and seeing how long is it, that they've been up. Could be used with something like Pingdom, to monitor this endpoint.\n
     - examples: [{contentType=application/json, example={
  "startup" : "2000-01-23T04:56:07.000+0000",
  "state" : "aeiou",
  "uptime" : 123
}}]

     - returns: RequestBuilder<Stats> 
     */
    public class func statsWithRequestBuilder() -> RequestBuilder<Stats> {
        let path = "/"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<Stats>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

}
