//
// CreateAccountRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Both the amount and customer are required. If you need to create a new account with no amount on it, just set the amount to 0.\n */
public class CreateAccountRequest: JSONEncodable {

    public var amount: Double?
public var customer: CustomerID?
public var name: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["amount"] = self.amount
        nillableDictionary["customer"] = self.customer?.encodeToJSON()
        nillableDictionary["name"] = self.name
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
