//
// Customer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Customer: JSONEncodable {

    /** can&#39;t be overwritten */
    public var created: NSDate?
public var name: String?
public var id: String?
public var accounts: [Account]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["created"] = self.created?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["id"] = self.id
        nillableDictionary["accounts"] = self.accounts?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
