//
// Stats.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Useful for debugging - pinging your servers and seeing how long is it, that they&#39;ve been up.\n */
public class Stats: JSONEncodable {

    public var state: String?
public var startup: NSDate?
public var uptime: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["state"] = self.state
        nillableDictionary["startup"] = self.startup?.encodeToJSON()
        nillableDictionary["uptime"] = self.uptime?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
